### ISSUE TITLE
unable to pull discussions for offices with a slash in the office name

### ISSUE THREAD

**Issue by jakewarren** [cbrown83/Alexa_NWS_Forecast_Discussion#1]
The following offices aren't picked up by the skill, likely because they contain a slash:

```
Austin/San Antonio, TX		EWX
Dallas/Fort Worth, TX		FWD
Denver/Boulder, CO		BOU
Midland/Odessa, TX		MAF
```

**Comment by cbrown83** [comment]
Pushed commit to fix this issue - these offices should get picked up right now. I will update the Alexa skill code momentarily.

**Comment by jakewarren** [comment]
thanks @cbrown83! I can confirm that your fix did resolve the issue.
